### ISSUE TITLE
Flag Hoisting

### ISSUE THREAD

**Issue by solomonshalom** [krikienoid/flagwaver#64] opened 2022-08-03 08:36 UTC
Hey Man!

Would be cool if you can do something like this ->
![image](https://thumbs.gfycat.com/BelovedFlawedCivet-size_restricted.gif)
Basically like when a user clicks a button, it goes up in the sky

**Comment by Bluellama2022** [comment] 2022-12-18 13:22
I think it would be cool.

**Comment by krikienoid** [comment] 2023-02-19 16:46
Thanks for your feedback, marking this as a duplicate of #44.

**Closed by krikienoid** 2023-02-19 16:46 UTC
